## Завдання 1


In [1]:
import numpy as np

arr = np.random.randint(0, 51, 20)
print("Вихідний масив:", arr)

threshold = int(input("Введіть порогове значення: "))

count_greater = np.sum(arr > threshold)
print(f"Кількість елементів більших за {threshold}: {count_greater}")

max_val = np.max(arr)
max_idx = np.argmax(arr)
print(f"Максимальне значення: {max_val}, позиція першої появи (індекс): {max_idx}")

sorted_arr = np.sort(arr)[::-1]
print("Відсортований масив (за спаданням):", sorted_arr)

Вихідний масив: [24 27 23  1 36 42 33  5 19  9 32  1  5 12 15 44 12 13 42 39]


Введіть порогове значення:  2


Кількість елементів більших за 2: 18
Максимальне значення: 44, позиція першої появи (індекс): 15
Відсортований масив (за спаданням): [44 42 42 39 36 33 32 27 24 23 19 15 13 12 12  9  5  5  1  1]


## Завдання 2


In [2]:
import numpy as np

low = int(input("Введіть нижню межу діапазону: "))
high = int(input("Введіть верхню межу діапазону: "))

matrix = np.random.randint(low, high + 1, (5, 5))
print("\nВихідна матриця 5x5:\n", matrix)

main_diag = np.diag(matrix)
print("\nГоловна діагональ:", main_diag)

diag_sum = np.sum(main_diag)
print("Сума елементів головної діагоналі:", diag_sum)

matrix_lower = np.tril(matrix)
print("\nМатриця після обнулення елементів вище головної діагоналі:\n", matrix_lower)

Введіть нижню межу діапазону:  2
Введіть верхню межу діапазону:  5



Вихідна матриця 5x5:
 [[3 5 4 3 3]
 [3 3 4 2 3]
 [2 3 2 4 4]
 [3 4 5 5 4]
 [3 2 5 3 2]]

Головна діагональ: [3 3 2 5 2]
Сума елементів головної діагоналі: 15

Матриця після обнулення елементів вище головної діагоналі:
 [[3 0 0 0 0]
 [3 3 0 0 0]
 [2 3 2 0 0]
 [3 4 5 5 0]
 [3 2 5 3 2]]


## Завдання 3

In [3]:
import numpy as np

start = int(input("Введіть початок діапазону: "))
end = int(input("Введіть кінець діапазону: "))

matrix_6x5 = np.random.randint(start, end + 1, (6, 5))
print("\nМатриця 6x5:\n", matrix_6x5)

row_sums = np.sum(matrix_6x5, axis=1)
print("\nСума елементів у кожному рядку:", row_sums)

col_maxs = np.max(matrix_6x5, axis=0)
print("Максимальні значення за кожним стовпчиком:", col_maxs)

Введіть початок діапазону:  1
Введіть кінець діапазону:  10



Матриця 6x5:
 [[ 1  3  8 10  1]
 [ 5  8  1  7  5]
 [ 1  1  1 10  7]
 [10  4  4  8  8]
 [ 5  3  5  4  7]
 [ 7  4  7  4  4]]

Сума елементів у кожному рядку: [23 26 20 34 24 26]
Максимальні значення за кожним стовпчиком: [10  8  8 10  8]


## Завдання 4


In [4]:
import numpy as np

low = int(input("Введіть нижню межу (напр., -20): "))
high = int(input("Введіть верхню межу (напр., 20): "))

arr_15 = np.random.randint(low, high + 1, 15)
print("\nВихідний масив:", arr_15)

neg_arr = arr_15[arr_15 < 0]
print("Від'ємні елементи:", neg_arr)

mod_arr = np.where(arr_15 < 0, 0, arr_15)
print("Змінена копія (від'ємні замінено на 0):", mod_arr)

zero_count = np.sum(mod_arr == 0)
print("Кількість нульових елементів у зміненому масиві:", zero_count)

Введіть нижню межу (напр., -20):  -20
Введіть верхню межу (напр., 20):  20



Вихідний масив: [ 16   7  17   6   2   1  10  20  -4 -18  11   5  10 -12  -5]
Від'ємні елементи: [ -4 -18 -12  -5]
Змінена копія (від'ємні замінено на 0): [16  7 17  6  2  1 10 20  0  0 11  5 10  0  0]
Кількість нульових елементів у зміненому масиві: 4


## Завдання 5

In [5]:
import numpy as np

length = int(input("Введіть довжину масивів: "))

arr1 = np.random.randint(0, 11, length)
arr2 = np.random.randint(10, 21, length)

print("\nПерший масив (0-10):", arr1)
print("Другий масив (10-20):", arr2)

combined_arr = np.concatenate((arr1, arr2))
print("\nОб'єднаний масив:", combined_arr)

sum_arr = arr1 + arr2
diff_arr = arr1 - arr2
print("\nПоелементне додавання:", sum_arr)
print("Поелементна різниця (перший - другий):", diff_arr)

Введіть довжину масивів:  100



Перший масив (0-10): [10  6  2  1 10  5  4  6  4  8  0  2  1  4  2  7 10  2  6  0  2  2  3  1
  3  2  1  6  8  3  7 10  8  3  6  4 10  3  8  0  0  1  6  0  9  4  2  0
  9  1  3  9  1  5 10  9  3  9  0  0  5 10  5 10  3  2  3  7  9  3  1  8
  1  9 10  8  1 10  9  9  0  1 10  0  1  7  5  0  3  4  9  6  1  4  7  9
  3  8  6  5]
Другий масив (10-20): [11 17 19 13 20 13 12 19 16 15 20 12 15 16 19 13 16 14 17 12 13 14 15 15
 19 20 11 15 18 15 15 19 15 16 11 16 10 17 13 20 17 11 18 16 14 13 11 15
 18 12 10 20 16 13 10 19 20 20 18 12 16 12 16 13 17 19 18 18 13 19 18 19
 15 10 15 15 17 10 10 12 10 17 19 11 13 11 20 17 11 16 17 20 12 15 10 13
 14 20 18 11]

Об'єднаний масив: [10  6  2  1 10  5  4  6  4  8  0  2  1  4  2  7 10  2  6  0  2  2  3  1
  3  2  1  6  8  3  7 10  8  3  6  4 10  3  8  0  0  1  6  0  9  4  2  0
  9  1  3  9  1  5 10  9  3  9  0  0  5 10  5 10  3  2  3  7  9  3  1  8
  1  9 10  8  1 10  9  9  0  1 10  0  1  7  5  0  3  4  9  6  1  4  7  9
  3  8  6  5 11 17 19 13 20 13 12

## Завдання 6


In [ ]:
import numpy as np

rows = int(input("Введіть кількість рядків вихідної матриці: "))
cols = int(input("Введіть кількість стовпців вихідної матриці: "))

total_elements = rows * cols
matrix_seq = np.arange(total_elements).reshape(rows, cols)
print("\nВихідна матриця:\n", matrix_seq)

new_rows = int(input("\nВведіть нову кількість рядків: "))
new_cols = int(input("Введіть нову кількість стовпців: "))

if total_elements != (new_rows * new_cols):
    print(f"Помилка: неможливо перетворити матрицю з {total_elements} елементів у форму {new_rows}x{new_cols}.")
else:
    new_matrix = matrix_seq.reshape(new_rows, new_cols)
    print("\nПеретворена матриця:\n", new_matrix)

    row_mins = new_matrix.min(axis=1)
    row_maxs = new_matrix.max(axis=1)
    print("\nМінімальні значення в кожному рядку:", row_mins)
    print("Максимальні значення в кожному рядку:", row_maxs)

    total_sum = new_matrix.sum()
    print("\nЗагальна сума всіх елементів нової матриці:", total_sum)

Введіть кількість рядків вихідної матриці:  10
Введіть кількість стовпців вихідної матриці:  5



Вихідна матриця:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
