# NumPy

## Завдання 1
* Створіть одновимірний масив із 10 випадкових чисел від 0 до 100.
* Збережіть масив у змінну і виведіть його на екран.
* Знайдіть мінімальне, максимальне та середнє значення масиву за допомогою вбудованих функцій NumPy.
* Відсортуйте масив за зростанням і виведіть результат.
* Відобразіть масив до і після сортування.

In [1]:
# pip install numpy

In [2]:
import numpy as np

In [3]:
rand10 = np.random.randint(0, 100, size=10)
rand10

array([30, 95, 54, 71, 63, 63, 74, 39, 43, 65], dtype=int32)

In [4]:
print("мінімальне: %d, максимальне %d та середнє значення масиву %f" % (
    np.min(rand10), 
    np.max(rand10), 
    np.mean(rand10)
))

мінімальне: 30, максимальне 95 та середнє значення масиву 59.700000


In [5]:
print(rand10, np.sort(rand10), sep='\n')

[30 95 54 71 63 63 74 39 43 65]
[30 39 43 54 63 63 65 71 74 95]


## Завдання 2
* Створіть двовимірний масив розміром 4×4, заповнений випадковими цілими числами від 1 до 50.
* Виведіть масив у читабельному вигляді (у вигляді таблиці).
* Знайдіть суму елементів за кожним рядком і за кожним стовпчиком (використовуйте параметр axis).
* Визначте загальне середнє значення масиву.
* Виведіть усі результати в зручному вигляді
(наприклад: "Суми за рядками: ...","Суми за стовпцями: ...").

In [6]:
rand_4_4 = np.random.randint(1, 20, size=(4,4))
rand_4_4

array([[ 2, 18, 19, 17],
       [ 4,  9, 17, 19],
       [ 8, 15, 19, 11],
       [14,  3, 15, 18]], dtype=int32)

In [7]:
print(np.sum(rand_4_4, axis=0),  # columns
      np.sum(rand_4_4, axis=1),  # rows
      np.mean(rand_4_4))

[28 45 70 65] [56 49 53 50] 13.0


In [8]:
print(*["%s | %d" % (k,v) for (k,v) in 
        zip(rand_4_4, np.sum(rand_4_4, axis=1))], 
      "-----------------",
      np.sum(rand_4_4, axis=0), sep='\n', end=' | ')
print(np.mean(rand_4_4))

[ 2 18 19 17] | 56
[ 4  9 17 19] | 49
[ 8 15 19 11] | 53
[14  3 15 18] | 50
-----------------
[28 45 70 65] | 13.0


## Завдання 3
* Створіть масив розміром 3×5, заповнений числами від 0 до 14.
* Виведіть вихідний масив.
* Виконайте транспонування масиву (рядки стають стовпцями, а стовпці — рядками).
* Застосуйте операцію reshape, щоб отримати масив 5×3.
* Відобразіть результати на екран.

In [11]:
rand_3_5 = np.random.randint(0, 14, size=(3,5))
rand_3_5

array([[11,  6,  6, 11, 11],
       [ 1, 12,  5,  7,  8],
       [ 8,  4,  7,  9,  7]], dtype=int32)

In [14]:
print("Форма масиву: ", rand_3_5.shape)

Форма масиву:  (3, 5)


In [15]:
trans = np.transpose(rand_3_5)
print("Транспонування:\n", trans)
print("Форма транспонованого масиву: ", trans.shape)

Транспонування:
 [[11  1  8]
 [ 6 12  4]
 [ 6  5  7]
 [11  7  9]
 [11  8  7]]
Форма транспонованого масиву:  (5, 3)


In [16]:
resh = np.reshape(rand_3_5, shape=(5,3))
print("Зміна розмірності (решейпінг):\n", resh)
print("Форма нового масиву: ", resh.shape)
# дія решейпінгу - серіалізація вихідного масиву 
# (перенесення в один вимір один-за-одним)
# та наступний переділ згідно з заданими
# розмірностями 

Зміна розмірності (решейпінг):
 [[11  6  6]
 [11 11  1]
 [12  5  7]
 [ 8  8  4]
 [ 7  9  7]]
Форма нового масиву:  (5, 3)


## Завдання 4
* Створіть масив розміром 10×10, заповнений випадковими числами з плаваючою крапкою від 0 до 1.
* Знайдіть мінімальне та максимальне значення в усьому масиві.
* Визначте індекси мінімального та максимального елементів
(наприклад: (рядок, стовпець)).
* Виведіть сам масив і окремо знайдені значення разом з їхніми індексами.

In [21]:
rand_10_10 = np.random.rand(10,10)  # виведення великих об'ємів незручне
np.set_printoptions(precision=4)    # Тільки для виведення можна обмежити
print(*rand_10_10, sep='\n')        # точність (тільки для масивів)

[[0.6632 0.083  0.1554 0.0546 0.5034 0.1882 0.9687 0.2179 0.1625 0.7854]
 [0.2161 0.586  0.3867 0.1304 0.4463 0.8438 0.1076 0.5167 0.8255 0.7435]
 [0.4349 0.2352 0.654  0.0949 0.5893 0.1696 0.2429 0.1134 0.2579 0.668 ]
 [0.2293 0.9583 0.832  0.6329 0.8505 0.0243 0.974  0.2866 0.3641 0.8057]
 [0.547  0.5347 0.9345 0.5953 0.3832 0.6447 0.4854 0.241  0.8912 0.7447]
 [0.6778 0.1668 0.0788 0.0453 0.4634 0.7188 0.9047 0.7797 0.4899 0.6434]
 [0.3403 0.6885 0.8958 0.7252 0.6523 0.3213 0.2827 0.2228 0.7491 0.0276]
 [0.3281 0.3011 0.96   0.4198 0.608  0.8472 0.5456 0.3519 0.0572 0.7427]
 [0.6792 0.4194 0.7882 0.0977 0.4801 0.3159 0.6158 0.0407 0.1749 0.9995]
 [0.9563 0.1095 0.0279 0.2684 0.4203 0.821  0.3412 0.7958 0.6011 0.8185]]


In [36]:
max_v = np.max(rand_10_10)
print("Максимальне значення у масиві: ", max_v)
max_i = np.argmax(rand_10_10)  # індекс суцільний - від самого початку масиву
print("Знаходиться за індексом: ", max_i)
# перераховуємо суцільний індекс на набір індексів по заданій формі масиву
max_coord = np.unravel_index(max_i, rand_10_10.shape)
print("Що відповідає сукупності індексів:", ", ".join(map(str, max_coord)))


Максимальне значення у масиві:  0.9995423862637304
Знаходиться за індексом:  89
Що відповідає сукупності індексів: 8, 9


In [37]:
min_v = np.min(rand_10_10)
print("Максимальне значення у масиві: ", min_v)
min_i = np.argmin(rand_10_10) 
print("Знаходиться за індексом: ", min_i)
min_coord = np.unravel_index(min_i, rand_10_10.shape)
print("Що відповідає сукупності індексів:", ", ".join(map(str, min_coord)))

Максимальне значення у масиві:  0.024321540804137065
Знаходиться за індексом:  35
Що відповідає сукупності індексів: 3, 5


## Завдання 5
* Створіть одновимірний масив із 15 випадкових цілих чисел від -10 до 10.
* Виведіть масив.
* За допомогою булевої індексації виберіть тільки додатні елементи.
* За допомогою булевої індексації виберіть тільки парні елементи.
* Виведіть обидва результати на екран.

In [38]:
rand_15 = np.random.randint(-10, 10, size=15)
print(rand_15)

[  4  -8 -10  -3  -6  -5 -10   7  -8   6  -4   0   5   3  -8]


In [44]:
res_pos = rand_15 > 0
print("Булева індексація дозволяє застосувати умову до масиву і одержати масив результатів:\n",
      res_pos)
print("Використання масиву булевих значень як індексу залишає лише ті елементи, для яких True:\n",
      rand_15[res_pos])
print("Кількість додатніх елементів:", np.count_nonzero(res_pos))

Булева індексація дозволяє застосувати умову до масиву і одержати масив результатів:
 [ True False False False False False False  True False  True False False
  True  True False]
Використання масиву булевих значень як індексу залишає лише ті елементи, для яких True:
 [4 7 6 5 3]
Кількість додатніх елементів: 5


In [46]:
print("Парні значення:", rand_15[rand_15 % 2 == 0])

Парні значення: [  4  -8 -10  -6 -10  -8   6  -4   0  -8]
